### ISSUE TITLE
FAILURE: Build failed with an exception.

### ISSUE THREAD

**Issue by life-Nd** [X-dea/SnakeEye#1]
Great work guys, i was able to successfully run **PlatformIO build** and **PlatformIO upload** but after doing **flutter pub get** and try to do **flutter run** on a physical Samsung the build fails.  
I am on a MACbook Pro (2012 intel), i installed opencv via brew with success but the error still appears, i also tried installing via the opencv website but i still get errors.

`
Launching lib/main.dart on SM A520W in debug mode...
* What went wrong:
Execution failed for task ':app:configureCMakeDebug[arm64-v8a]'.
> [CXX1405] error when building with cmake using /Users/lifen/Projects/MLX90640/Code/SnakeEye/android/app/src/main/cpp/CMakeLists.txt: Build command failed.
  Error while executing process /Users/lifen/SDKs/Android/sdk/cmake/3.22.1/bin/cmake with arguments {-H/Users/lifen/Projects/MLX90640/Code/SnakeEye/android/app/src/main/cpp -DCMAKE_SYSTEM_NAME=Android -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_SYSTEM_VERSION=21 -DANDROID_PLATFORM=android-21 -DANDROID_ABI=arm64-v8a -DCMAKE_ANDROID_ARCH_ABI=arm64-v8a -DANDROID_NDK=/Users/lifen/SDKs/Android/sdk/ndk/23.1.7779620 -DCMAKE_ANDROID_NDK=/Users/lifen/SDKs/Android/sdk/ndk/23.1.7779620 -DCMAKE_TOOLCHAIN_FILE=/Users/lifen/SDKs/Android/sdk/ndk/23.1.7779620/build/cmake/android.toolchain.cmake -DCMAKE_MAKE_PROGRAM=/Users/lifen/SDKs/Android/sdk/cmake/3.22.1/bin/ninja -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/Users/lifen/Projects/MLX90640/Code/SnakeEye/build/app/intermediates/cxx/Debug/2z58186g/obj/arm64-v8a -DCMAKE_RUNTIME_OUTPUT_DIRECTORY=/Users/lifen/Projects/MLX90640/Code/SnakeEye/build/app/intermediates/cxx/Debug/2z58186g/obj/arm64-v8a -DCMAKE_BUILD_TYPE=Debug -B/Users/lifen/Projects/MLX90640/Code/SnakeEye/android/app/.cxx/Debug/2z58186g/arm64-v8a -GNinja}
  -- Android: Targeting API '21' with architecture 'arm64', ABI 'arm64-v8a', and processor 'aarch64'
  -- Android: Selected unified Clang toolchain
  -- The C compiler identification is Clang 12.0.8
  -- The CXX compiler identification is Clang 12.0.8
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Check for working C compiler: /Users/lifen/SDKs/Android/sdk/ndk/23.1.7779620/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang - skipped
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Check for working CXX compiler: /Users/lifen/SDKs/Android/sdk/ndk/23.1.7779620/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang++ - skipped
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  -- Configuring incomplete, errors occurred!
  See also "/Users/lifen/Projects/MLX90640/Code/SnakeEye/android/app/.cxx/Debug/2z58186g/arm64-v8a/CMakeFiles/CMakeOutput.log".

  CMake Error at CMakeLists.txt:47 (find_package):
    By not providing "FindOpenCV.cmake" in CMAKE_MODULE_PATH this project has
    asked CMake to find a package configuration file provided by "OpenCV", but
    CMake did not find one.

    Could not find a package configuration file provided by "OpenCV" with any
    of the following names:

      OpenCVConfig.cmake
      opencv-config.cmake

    Add the installation prefix of "OpenCV" to CMAKE_PREFIX_PATH or set
    "OpenCV_DIR" to a directory containing one of the above files.  If "OpenCV"
    provides a separate development package or SDK, be sure it has been
    installed.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 17s
Running Gradle task 'assembleDebug'...                             19.4s
Exception: Gradle task assembleDebug failed with exit code 1`

flutter doctor:
`Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.7.3, on macOS 13.1 22C65 darwin-x64, locale en-CA)
Checking Android licenses is taking an unexpectedly long time...[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] VS Code (version 1.75.1)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

• No issues found!
`
.zshrc
`
 export NVM_DIR="$HOME/.nvm"
    [ -s "$(brew --prefix)/opt/nvm/nvm.sh" ] && \. "$(brew --prefix)/opt/nvm/nvm.sh" 
    [ -s "$(brew --prefix)/opt/nvm/etc/bash_completion.d/nvm" ] && \. "$(brew --prefix)/opt/nvm/etc/bash_completion.d/nvm" 

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" 
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  
export ANDROID_HOME=Users/lifen/SDKs/android/sdk
export ANDROID_SDK_ROOT=$ANDROID_HOME
export ANDROID_AVD_HOME=$HOME/.android/avd

export PATH="$PATH:$HOME/SDKs/flutter/bin"

export JAVA_HOME=/Applications/Android\ Studio.app/Contents/jre/Contents/Home
export ANDROID_HOME="$HOME/Library/Android/sdk"
export PATH="$ANDROID_HOME/tools:$ANDROID_HOME/tools/bin:$ANDROID_HOME/platform-tools:$PATH"

export PATH="/Applications/CMake.app/Contents/bin":"$PATH"

export PATH="/Users/lifen/Library/Python/3.9/bin":"$PATH"

export PATH="$PATH:$HOME/opencv"
export PATH="$PATH:$HOME/build_opencv"
export OpenCV_DIR=Users/lifen/opencv
export CMAKE_PREFIX_PATH=Users/lifen/opencv:$CMAKE_PREFIX_PATH

export LDFLAGS="-L/usr/local/opt/zlib/lib"
export CPPFLAGS="-I/usr/local/opt/zlib/include"

export CPATH=`xcrun --show-sdk-path`/usr/include

export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME="robbyrussell"
plugins=(git zsh-autosuggestions sudo web-search copyfile dirhistory history jsontools macos)
source $ZSH/oh-my-zsh.sh
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  
`
Any help to get it running would be greatly appreciated. Maybe my .zshrc is not set properly or i am missing something.

**Comment by ctrysbita** [comment]
This app depends on OpenCV Android SDK. Place the official sdk in `third_party/opencv-android` then it should work.

**Comment by life-Nd** [comment]
Hi thanks for the responds i actually found that yesterday and i added the opencv-android and the error `Could not find a package configuration file provided by "OpenCV"` **disappeared** but then another error came up i was trying to fix it before submitting a pull request to modify the ReadMe.md to give a steps by steps for others to be able to run the program.
Right now the error is: 
` 
SnakeEye flutter run
Launching lib/main.dart on SM A520W in debug mode...

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:buildCMakeDebug[arm64-v8a]'.
> Build command failed.
  Error while executing process /Users/lifen/SDKs/Android/sdk/cmake/3.18.1/bin/ninja with arguments {-C /Users/lifen/Projects/SnakeEye/android/app/.cxx/Debug/1uw4t5c2/arm64-v8a SnakeEye}
  ninja: Entering directory `/Users/lifen/Projects/SnakeEye/android/app/.cxx/Debug/1uw4t5c2/arm64-v8a'
  [1/1] Linking CXX shared library /Users/lifen/Projects/SnakeEye/build/app/intermediates/cxx/Debug/1uw4t5c2/obj/arm64-v8a/libSnakeEye.so
  FAILED: /Users/lifen/Projects/SnakeEye/build/app/intermediates/cxx/Debug/1uw4t5c2/obj/arm64-v8a/libSnakeEye.so 
  : && /Users/lifen/SDKs/Android/sdk/ndk/23.1.7779620/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang++ --target=aarch64-none-linux-android21 --gcc-toolchain=/Users/lifen/SDKs/Android/sdk/ndk/23.1.7779620/toolchains/llvm/prebuilt/darwin-x86_64 --sysroot=/Users/lifen/SDKs/Android/sdk/ndk/23.1.7779620/toolchains/llvm/prebuilt/darwin-x86_64/sysroot -fPIC -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security  -std=c++11  -fexceptions -lc++ -fno-limit-debug-info  -static-libstdc++ -Wl,--build-id=sha1 -Wl,--no-rosegment -Wl,--fatal-warnings -Wl,--no-undefined -Qunused-arguments -shared -Wl,-soname,libSnakeEye.so -o /Users/lifen/Projects/SnakeEye/build/app/intermediates/cxx/Debug/1uw4t5c2/obj/arm64-v8a/libSnakeEye.so CMakeFiles/SnakeEye.dir/image.cpp.o  -llog  /Users/lifen/Projects/SnakeEye/third_party/opencv-android/sdk/native/libs/arm64-v8a/libopencv_java3.so  -ljnigraphics  -llog  -ldl  -lz  -latomic -lm && :
  ld: error: found local symbol '_edata' in global part of symbol table in file /Users/lifen/Projects/SnakeEye/third_party/opencv-android/sdk/native/libs/arm64-v8a/libopencv_java3.so
  ld: error: found local symbol '__end__' in global part of symbol table in file /Users/lifen/Projects/SnakeEye/third_party/opencv-android/sdk/native/libs/arm64-v8a/libopencv_java3.so
  ld: error: found local symbol '__bss_end__' in global part of symbol table in file /Users/lifen/Projects/SnakeEye/third_party/opencv-android/sdk/native/libs/arm64-v8a/libopencv_java3.so
  ld: error: found local symbol '_bss_end__' in global part of symbol table in file /Users/lifen/Projects/SnakeEye/third_party/opencv-android/sdk/native/libs/arm64-v8a/libopencv_java3.so
  ld: error: found local symbol '__bss_start__' in global part of symbol table in file /Users/lifen/Projects/SnakeEye/third_party/opencv-android/sdk/native/libs/arm64-v8a/libopencv_java3.so
  ld: error: found local symbol '_end' in global part of symbol table in file /Users/lifen/Projects/SnakeEye/third_party/opencv-android/sdk/native/libs/arm64-v8a/libopencv_java3.so
  ld: error: found local symbol '__bss_start' in global part of symbol table in file /Users/lifen/Projects/SnakeEye/third_party/opencv-android/sdk/native/libs/arm64-v8a/libopencv_java3.so
  clang++: error: linker command failed with exit code 1 (use -v to see invocation)
  ninja: build stopped: subcommand failed.



* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 17s
Running Gradle task 'assembleDebug'...                             19.7s
Exception: Gradle task assembleDebug failed with exit code 1
`
Do you know how i could resolve it?

**Comment by ctrysbita** [comment]
It seems the link target is wrong since we don't need libopencv_java3.so (the opencv library is statically-linked)
Use the SDK here: https://github.com/opencv/opencv/releases/download/4.7.0/opencv-4.7.0-android-sdk.zip
Place it like this:
![image](https://user-images.githubusercontent.com/8357481/220976517-84d763ee-787d-48c4-8504-7df26d7bd6f5.png)
Then `flutter build apk` should work.

**Comment by life-Nd** [comment]
Thank you very much i was finally able to flash the ESP32 with the firmware then install the app on a Samsung S21.

The steps i followed:
# Firmware 

**1. Modify `platformio.ini`**
- Change  platform, board depending on the device used: 
```
platform = espressif32@6.0.1
board = NodeMCU-32S
```
**2. Add opencv-android sdk** 
- Download the SDK from  https://github.com/opencv/opencv/releases/download/4.7.0/opencv-4.7.0-android-sdk.zip
- Extract the folders and copy them in SnakeEye/third_party/opencv-android

**3. Modify `pubspec.yaml`**
- Comment out: 
```
#  assets:
#    - res/ 
```
**4. Modify `SnakeEye/firmware/lib/MLX90640/MLX90640_I2C_Driver.cpp`**
- To fix: error: 'BUFFER_LENGTH' was not declared :
The Wire module now defines I2C_BUFFER_LENGTH no longer BUFFER_LENGTH
Change:
   **BUFFER_LENGTH** to **I2C_BUFFER_LENGTH**

**5. Modify `SnakeEye/firmware/src/config.h`**
- To fix #define VERSION 1'00'00U expected ';' before '\x3030'
This is because the #define statement is a preprocessor directive that replaces any occurrence of VERSION in the code with the defined value. In this case, the VERSION is set to 10000, which is a decimal value. The U at the end is used to indicate that the value is an unsigned integer.
Change: 
 **#define VERSION 1'00'00U** to **#define VERSION 10000U**

**6. Modify `SnakeEye/firmware/lib/MLX90640/MLX90640_I2C_Driver.cpp`**
- Add the pins connected to the MLX90640 under the last `#include`
**❗️ _These values depend on your wiring_**
```
 #define I2C_SDA 21
 #define I2C_SCL 23 
```
- Add the pins to be used by the Wire
`void MLX90640_I2CInit() {   Wire.begin(); }`
**to** 
`void MLX90640_I2CInit() {   Wire.begin(I2C_SDA, I2C_SCL); }`

#Phone

**1. Wifi connection**
- Search for **SnakeEye** in the wifi networks
- Add password **5nakeEye** (it's a five at the begining)
- It should connect and say **Connected without internet**

# Flutter

**1. flutter pub get**
- From the command line in the root of the project SnakeEye/ 
`flutter pub get`

**2. Modify `SnakeEye/lib/connection/udp_connection.dart`**
- Issue with the data being split in multiple packets depending on the maximum packet size supported by the network and the device. 
To fix this i had to to modify: 

```
@override
  Stream<Float32List> receiveFrames() async* {
    final stream = _stream;
    if (stream == null) {
      throw StateError('disconnected');
    }

    _socket?.send([Command.startFrames.index], address, port);

    await for (var data in stream) {
      if (data.lengthInBytes != rawFrameLength) continue;
      yield data.buffer.asFloat32List();
    }
  } 
```

  to: 

```
  @override
  Stream<Float32List> receiveFrames() async* {
    final stream = _stream;
    if (stream == null) {
      throw StateError('disconnected');
    }

    _socket?.send([Command.startFrames.index], address, port);

/ / The modifications ⬇️
    final buffer = BytesBuilder();
// The data will be added to the buffer until the defined rawFrameLength is reached 
// then the buffer will be yielded before being cleared

    await for (var data in stream) {
      buffer.add(data);
      if (buffer.length == rawFrameLength) {
        yield buffer.toBytes().buffer.asFloat32List();
        buffer.clear();
      }
    }
  }
```


**3. Connect the device via USB**
- Tried with a physical device (Samsung S21 and Galaxy A5)

**4. flutter run** 
- From the command line in the root of the project SnakeEye/ 
`flutter run`

❗️ **Make sure the ESP32 is always connected via wifi**

# Everything should be working 🙂
